version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
       # volume for config
       - /home/dmitrijd/node_docker/config_nginx/nginx.conf:/etc/nginx/nginx.conf
       # volume for static
       - /home/dmitrijd/node_docker/stat:/stat
    # you can use in nginx.conf http://node_service:port
    links:
      - node_service
    # 5000 external, 80 container
    ports:
      - 5000:80
    # start after
    depends_on:
       - node_service
  node_service:
    container_name: node_service
    build:
      context: /home/dmitrijd/node_docker/
      dockerfile: Dockerfile
    volumes:
      # for log
      - /home/dmitrijd/node_docker/log:/node_docker/log
      # for watching changing in code and restart via pm2-watch
      - /home/dmitrijd/node_docker/app:/node_docker/app
    # you can use in node js mysql.host as "db"
    links:
      - mysql:db
    # start after
    depends_on:
       - mysql
  mysql:
    image: mysql
    container_name: mysql
    # use standard old auth
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
    volumes:
      - /home/dmitrijd/node_docker/mysql:/var/lib/mysql
