version: '3'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
       # volume for config
       - /home/dmitrijd/node_docker/config_nginx/nginx.conf:/etc/nginx/nginx.conf
    # you can use in nginx.conf http://node_service:port
    links:
      - node_service
    # 5000 external, 80 container
    ports:
      - 5000:80
  node_service:
    build:
      context: /home/dmitrijd/node_docker/
      dockerfile: Dockerfile
    # 5000 external, 80 container
    # ports:
    #   - 5000:80
    volumes:
      - /home/dmitrijd/node_docker/log:/node_docker/log
      - /home/dmitrijd/node_docker/app:/node_docker/app
    # you can use in node js mysql.host as "db"
    links:
      - mysql:db
    # start after
    depends_on:
       - mysql
       # - nginx
  mysql:
    image: mysql
    # use standard old auth
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
    volumes:
      - /home/dmitrijd/node_docker/mysql:/var/lib/mysql
